"""
make_macros.py
==============
Reads theory_results.json and gfi_results.json and writes results_macros.tex,
a set of \\renewcommand definitions consumed by main_revised.tex so that every
number in the paper is generated by the code.  ASCII output.
"""
from __future__ import annotations
import json, os


def load(f):
    return json.load(open(f, encoding="utf-8")) if os.path.exists(f) else {}


def fmt(x, nd=3):
    try:
        return ("%." + str(nd) + "g") % float(x)
    except Exception:
        return "--"


def main():
    th = load("theory_results.json")
    gf = load("gfi_results.json")
    L = []
    def cmd(name, val):
        L.append(r"\renewcommand{\%s}{%s}" % (name, val))

    # ---- theory ----
    sl = th.get("lemma1_fitted_slopes", {})
    cmd("resSlopeA", fmt(sl.get("alpha_0.7"), 4))
    cmd("resPredA", fmt(th.get("lemma1_predicted_slopes", {}).get("alpha_0.7"), 3))
    l2 = th.get("lemma2", {})
    cmd("resAlignSlack", fmt(l2.get("min_slack"), 3))
    cmd("resAlignHolds", "true" if l2.get("holds") else "approximately")
    lsc = th.get("lemma_sc", {})
    cmd("resScSlack", fmt(lsc.get("min_slack"), 3))
    suc = th.get("theorem2_final_success", {})
    cmd("resGlobalRast", fmt(suc.get("Rastrigin"), 2))
    cmd("resGlobalAck", fmt(suc.get("Ackley"), 2))
    cmd("resGlobalGri", fmt(suc.get("Griewank"), 2))
    cmd("resGlobalSch", fmt(suc.get("Schwefel"), 2))
    cmd("resGeomRate", fmt(th.get("theorem2_geometric_decay_rate"), 3))

    # ---- gfi tuning ----
    bc = gf.get("tuning_best_cost", {})
    cmd("resCostTFABC", fmt(bc.get("TF-ABC"), 4))
    cmd("resCostABC", fmt(bc.get("ABC"), 4))
    cmd("resCostPSO", fmt(bc.get("PSO"), 4))
    cmd("resCostGA", fmt(bc.get("GA"), 4))
    # distributional statistics over independent runs
    tq = gf.get("tuning_quality", {})
    for key, tag in (("TF-ABC", "TFABC"), ("ABC", "ABC"),
                     ("PSO", "PSO"), ("GA", "GA")):
        d = tq.get(key, {})
        cmd("resMean" + tag, fmt(d.get("mean"), 3))
        cmd("resStd" + tag, fmt(d.get("std"), 2))
        cmd("resMed" + tag, fmt(d.get("median"), 3))
        cmd("resBest" + tag, fmt(d.get("best"), 4))
    ts = gf.get("tuning_stats", {})
    cmd("resNrun", str(ts.get("nrun", 30)))
    cmd("resFriedP", fmt(ts.get("friedman_p"), 2))
    wv = ts.get("wilcoxon_vs_TFABC", {})
    cmd("resWilcoxABC", fmt(wv.get("ABC"), 2))
    cmd("resWilcoxPSO", fmt(wv.get("PSO"), 2))
    cmd("resWilcoxGA", fmt(wv.get("GA"), 2))
    rank = gf.get("tuning_rank_by_mean", [])
    cmd("resRank", r" $<$ ".join(rank) if rank else "--")
    bt = gf.get("tuning_best_theta", {}).get("TF-ABC", [None] * 5)
    for nm, v in zip(["resKp", "resKi", "resKd", "resMu", "resNu"], bt):
        cmd(nm, fmt(v, 4))
    pt = gf.get("pid_theta", [None] * 5)
    for nm, v in zip(["resKpP", "resKiP", "resKdP"], pt[:3]):
        cmd(nm, fmt(v, 4))

    # ---- step / thd / observer ----
    sr = gf.get("step_response", {})
    cmd("resDevF", fmt(sr.get("fopid_max_dev"), 3))
    cmd("resDevP", fmt(sr.get("pid_max_dev"), 3))
    cmd("resSetF", fmt(sr.get("fopid_settle"), 3))
    cmd("resSetP", fmt(sr.get("pid_settle"), 3))
    cmd("resDevImp", fmt(sr.get("dev_improvement_pct"), 3))
    cmd("resIseF", fmt(sr.get("fopid_ise"), 3))
    cmd("resIseP", fmt(sr.get("pid_ise"), 3))
    cmd("resIseImp", fmt(sr.get("ise_improvement_pct"), 3))
    cmd("resIrefPk", fmt(sr.get("fopid_iref_peak"), 3))
    cmd("resIrawPk", fmt(sr.get("fopid_iraw_peak"), 3))
    cmd("resDevFv", fmt(sr.get("fopid_max_dev"), 2))
    cmd("resDevPv", fmt(sr.get("pid_max_dev"), 2))
    imp = gf.get("impedance", {})
    cmd("resImpN", str(imp.get("n_points", 14)))
    cmd("resPidUnstable", str(imp.get("pid_unstable_count", 0)))
    td = gf.get("thd", {})
    cmd("resThdF", fmt(td.get("fopid"), 3))
    cmd("resThdP", fmt(td.get("pid"), 3))
    cmd("resVrmsF", fmt(td.get("fopid_vrms"), 3))
    cmd("resVrmsP", fmt(td.get("pid_vrms"), 3))
    cmd("resEssF", fmt(td.get("fopid_ess"), 2))
    cmd("resEssP", fmt(td.get("pid_ess"), 2))
    ob = gf.get("observer", {})
    cmd("resMAEi", fmt(ob.get("mae_iinv"), 3))
    cmd("resMAEv", fmt(ob.get("mae_vc"), 3))
    cmd("resMAEg", fmt(ob.get("mae_ig"), 3))

    with open("results_macros.tex", "w", encoding="utf-8") as fh:
        fh.write("% Auto-generated by make_macros.py -- do not edit.\n")
        fh.write("\n".join(L) + "\n")
    print("wrote results_macros.tex with %d macros" % len(L))

    # ---- loop-margin robustness table rows -> margins_table.tex ----
    import math
    mg = gf.get("margins", [])

    def mrow(r):
        g = r.get("gm_db")
        gms = ("$\\infty$" if (g is None or (isinstance(g, float) and math.isinf(g)))
               else "%.1f" % g)
        return ("%s & %.1f & %.2f & %.2f & %s & %.0f & %.2f \\\\"
                % (r.get("ctrl", ""), r.get("Lg_mH", 0), r.get("sinf", 0),
                   r.get("tinf", 0), gms, r.get("pm_deg", 0),
                   r.get("max_pole_re", 0)))
    if mg:
        # Write the COMPLETE tabular so the manuscript can \input it at the
        # table-float level (\input INSIDE a tabular, after \midrule, breaks the
        # alignment scanning -> "Misplaced \noalign").  LF newlines.
        head = (r"\begin{tabular}{llccccc}" "\n" r"\toprule" "\n"
                r"Controller & $L_g$ (mH) & $\norm{S}_\infty$ & $\norm{T}_\infty$"
                r" & GM (dB) & PM ($^\circ$) & $\max\operatorname{Re}\,p$ \\" "\n"
                r"\midrule" "\n")
        body = "\n".join(mrow(r) for r in mg) + "\n"
        foot = r"\bottomrule" "\n" r"\end{tabular}" "\n"
        with open("margins_table.tex", "w", encoding="utf-8", newline="\n") as fh:
            fh.write(head + body + foot)
        print("wrote margins_table.tex (full tabular, %d rows)" % len(mg))


if __name__ == "__main__":
    main()
